github CICD last test

diff --git a/.github/workflows/pipeline-backend.yml b/.github/workflows/pipeline-backend.yml
--- a/.github/workflows/pipeline-backend.yml
+++ b/.github/workflows/pipeline-backend.yml
@@ -40,11 +40,12 @@ jobs:
         run: |
           for module in ${{ env.MODULES }}; do
             echo "---------- $module ----------"
-            cd $module/$module
+            cd $module
             echo "Compiling the code..."
             mvn compile
             echo "Compile complete."
-            cd ../..
+            cd ..
+            cd ..
           done
 
   build:
@@ -67,7 +68,7 @@ jobs:
         run: |
           for module in ${{ env.MODULES }}; do
             echo "----------------------------------------------------- $module --------------------------------------------------------------------------"
-            cd $module/$module
+            cd $module
             echo "Building the code..."
             mvn package -DskipTests
             echo "Build complete."
@@ -80,7 +81,8 @@ jobs:
               echo "JAR file $JAR_FILE successfully built for $module"
             fi
 
-            cd ../..
+            cd ..
+            cd ..
           done
 
   build-image:
@@ -107,25 +109,25 @@ jobs:
 
       - name: Build & push Docker images
         run: |
-          for module in ${{ env.MODULES }}; do
-            echo "----------------------------------------------------- $module --------------------------------------------------------------------------"
-            cd $module/$module
-            echo "Copying JAR file for Docker build context..."
-            JAR_FILE=$(find target -name "*.jar")
-            cp $JAR_FILE .
-
-            echo "Building Docker image..."
-            module_name=$(basename $module | tr '[:upper:]' '[:lower:]')
-            docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest .
-            if [ $? -eq 0 ]; then
-              docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest
-              echo "Docker image for $module pushed to Docker Hub."
-            else
-              echo "Failed to build Docker image for $module."
-              exit 1
-            fi
-            cd ../..
-          done
+            for module in ${{ env.MODULES }}; do
+              echo "----------------------------------------------------- $module --------------------------------------------------------------------------"
+              cd $module/$module
+              echo "Copying JAR file for Docker build context..."
+              JAR_FILE=$(find target -name "*.jar")
+              cp $JAR_FILE .
+            
+              echo "Building Docker image..."
+              module_name=$(basename $module | tr '[:upper:]' '[:lower:]')
+              docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest .
+              if [ $? -eq 0 ]; then
+                docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest
+                echo "Docker image for $module pushed to Docker Hub."
+              else
+                echo "Failed to build Docker image for $module."
+                exit 1
+              fi
+              cd ../..
+            done
 
   deploy:
     runs-on: ubuntu-latest
