github CICD

diff --git a/.github/workflows/pipeline-backend.yml b/.github/workflows/pipeline-backend.yml
--- a/.github/workflows/pipeline-backend.yml
+++ b/.github/workflows/pipeline-backend.yml
@@ -109,26 +109,33 @@ jobs:
 
       - name: Build & push Docker images
         run: |
-            for module in ${{ env.MODULES }}; do
-              echo "----------------------------------------------------- $module --------------------------------------------------------------------------"
-              cd $module
-              echo "Copying JAR file for Docker build context..."
-              ls -l
-              JAR_FILE=$(find target -name "*.jar")
-              cp $JAR_FILE .
-            
-              echo "Building Docker image..."
-              module_name=$(basename $module | tr '[:upper:]' '[:lower:]')
-              docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest .
-              if [ $? -eq 0 ]; then
-                docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest
-                echo "Docker image for $module pushed to Docker Hub."
-              else
-                echo "Failed to build Docker image for $module."
-                exit 1
-              fi
-              cd ../..
-            done
+          echo "Modules: ${{ env.MODULES }}"
+          echo "Docker Hub Username: ${{ secrets.DOCKER_HUB_USERNAME }}"
+          for module in ${{ env.MODULES }}; do
+            echo "----------------------------------------------------- $module --------------------------------------------------------------------------"
+            cd $module || { echo "Failed to navigate to $module"; exit 1; }
+            echo "Copying JAR file for Docker build context..."
+            ls -l
+            if [ ! -d "target" ]; then
+              echo "Error: 'target' directory not found in $module"
+              exit 1
+            fi
+            ls -l target/
+            JAR_FILE=$(find target -name "*.jar" ! -name "*.jar.original")
+            if [ -z "$JAR_FILE" ]; then
+              echo "No JAR file found in target directory for module $module"
+              exit 1
+            fi
+            echo "JAR file to be copied: $JAR_FILE"
+            cp $JAR_FILE . || { echo "Failed to copy JAR file for module $module"; exit 1; }
+          
+            echo "Building Docker image..."
+            module_name=$(basename $module | tr '[:upper:]' '[:lower:]')
+            docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest . || { echo "Failed to build Docker image for $module"; exit 1; }
+            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${module_name}:latest || { echo "Failed to push Docker image for $module"; exit 1; }
+            echo "Docker image for $module pushed to Docker Hub."
+            cd ../..
+          done
 
   deploy:
     runs-on: ubuntu-latest
